version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: emyht_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5ZKhawvkF85TkTseSRK2zcic
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: emyht_redis_db
    command: ["redis-server", "--requirepass", "gPkpWa8Z4mw9FEMBedFf8fUa"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
