name: Compile Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend Compile Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./backend

      - name: Compile backend
        run: go build -o /dev/null ./...
        working-directory: ./backend

  frontend:
    name: Frontend Compile Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Compile frontend
        run: npx tsc --noEmit
        working-directory: ./frontend
